name: LoteriasApp
description: "Aplicativo para conferir resultados de loterias."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"  # Updated for Dart 3 and Flutter 3 compatibility

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1 
  cupertino_icons: ^1.0.8  # Latest stable version
  http: ^1.1.0  # Latest stable version for HTTP package
  intl: ^0.19.0  # Updated to the latest for internationalization support
  shared_preferences: ^2.3.0  # Includes latest APIs for improved performance
  google_mobile_ads: ^5.1.0  # Latest version with bug fixes and improvements
  google_mlkit_text_recognition: ^0.14.0
  image_picker: ^1.1.2
  image: ^4.2.0
  path_provider: 2.1.4
  material_design_icons_flutter: 7.0.7296
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0  # Updated to the latest linting recommendations

flutter:
  uses-material-design: true
  assets:
    - assets\images\Bilhete-Instruções.jpg
    - assets\images\Bilhete-Instrucoes-Detalhe.jpg